version: "3.7"

services:
    app:
        build:
            args:
                user: ${APP_USER}
                uid: 1000
            context: ../
            dockerfile: ./docker-compose/php/Dockerfile
        image: t4_php
        container_name: t4_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ../:/var/www
        networks:
            - t4

    db:
        image: mysql:5.7
        container_name: t4_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d  #mysql image will automatically import .sql files placed in the /docker-entrypoint-initdb.d directory
            - t4_mysql:/var/lib/mysql
        ports:
            - 3308:3306
        networks:
            - t4

    nginx:
        image: nginx:1.17-alpine
        container_name: t4_nginx
        restart: unless-stopped
        ports: 
            - 8111:80
        volumes: 
            - ../:/var/www
            - ./nginx:/etc/nginx/conf.d
        networks:
            - t4

networks:
    t4:
        driver: bridge

volumes:
    t4_mysql: